/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of Example.xs. Do not edit this file, edit Example.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Example.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <yatk/db/yadb.h>


#line 18 "Example.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 61 "Example.c"

XS(XS_Example_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Example_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "filename");
    {
	char*	filename = (char *)SvPV_nolen(ST(0));
#line 14 "Example.xs"
	yadb_start(filename);
#line 77 "Example.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Example_load); /* prototype to pass -Wmissing-prototypes */
XS(XS_Example_load)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 19 "Example.xs"
	RETVAL = yadb_load();
#line 98 "Example.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Example_save); /* prototype to pass -Wmissing-prototypes */
XS(XS_Example_save)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;
#line 26 "Example.xs"
	RETVAL = yadb_save();
#line 120 "Example.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Example_dump); /* prototype to pass -Wmissing-prototypes */
XS(XS_Example_dump)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 33 "Example.xs"
	yadb_dump();
#line 140 "Example.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Example_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Example_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "key, val");
    {
	char*	key = (char *)SvPV_nolen(ST(0));
	char*	val = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 40 "Example.xs"
	RETVAL = yadb_insert(key, val);
#line 163 "Example.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Example_upd); /* prototype to pass -Wmissing-prototypes */
XS(XS_Example_upd)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "key, val");
    {
	char*	key = (char *)SvPV_nolen(ST(0));
	char*	val = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 49 "Example.xs"
	RETVAL = yadb_update(key, val);
#line 187 "Example.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Example_del); /* prototype to pass -Wmissing-prototypes */
XS(XS_Example_del)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "key");
    {
	char*	key = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;
#line 57 "Example.xs"
	RETVAL = yadb_delete(key);
#line 210 "Example.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Example_get); /* prototype to pass -Wmissing-prototypes */
XS(XS_Example_get)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "key");
    {
	char*	key = (char *)SvPV_nolen(ST(0));
#line 65 "Example.xs"
	record_t record;
	HV* data;
#line 232 "Example.c"
	HV *	RETVAL;
#line 68 "Example.xs"
	if (yadb_select(key, &record)) {
		data = (HV*)sv_2mortal((SV*)newHV());

		hv_store_ent(data, newSVpv(record.key, 0), newSVpv(record.val, 0), 0);

		RETVAL = data;
	}
	else {
		XSRETURN_UNDEF;
	}
#line 245 "Example.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Example); /* prototype to pass -Wmissing-prototypes */
XS(boot_Example)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Example::init", XS_Example_init, file);
        newXS("Example::load", XS_Example_load, file);
        newXS("Example::save", XS_Example_save, file);
        newXS("Example::dump", XS_Example_dump, file);
        newXS("Example::add", XS_Example_add, file);
        newXS("Example::upd", XS_Example_upd, file);
        newXS("Example::del", XS_Example_del, file);
        newXS("Example::get", XS_Example_get, file);
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

