######################################################################
# Automatically generated by qmake (2.00a) Sex Nov 17 05:33:23 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bat.h dragon.h monster.h serpent.h summoner.h
SOURCES += bat.cpp dragon.cpp main.cpp monster.cpp serpent.cpp summoner.cpp


LIBS    += -Llib -lmonster -ldl