######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 28 23:14:32 2009
######################################################################

TEMPLATE = lib
CONFIG = dll
TARGET = ../../lib/cat
DEPENDPATH += .
INCLUDEPATH += .

# Input
INCLUDES += ../../src/cat.h
SOURCES += ../../src/cat.cpp
