######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 28 22:48:45 2009
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += zoo.pro
