######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 17 17:40:06 2009
######################################################################

TEMPLATE = lib
TARGET = yadb
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += priv_types.h pub_types.h yadb.h yadb_data.h
SOURCES += yadb.c yadb_data.c
